[package]
name = "wordle-analyzer"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Christoph J. Scherr <software@cscherr.de>"]
license = "MIT"
description = "Play, Analyze and Benchmark Wordle  / Wordle Strategies"
readme = "README.md"
homepage = "https://git.cscherr.de/PlexSheep/wordle-analyzer"
repository = "https://git.cscherr.de/PlexSheep/wordle-analyzer"
keywords = ["wordle", "benchmark"]


[dependencies]

